name: Run Selenium Tests

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: >-
          --privileged

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -f Dockerfile.chrome -t pytest-allure-tester .

    - name: Run Parallel Tests
      run: |
        mkdir -p reports
        docker run --rm -v ${{ github.workspace }}/reports:/app/reports pytest-allure-tester -n auto

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html